version: 2.1

jobs:
  
  compile-project:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run:
          name: "Compile project"
          command: "mvn compile"


workflows:
  Notepad-CircleCi: 
    jobs:
      - compile-project
